package GUI;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel; 
/**
 *
 * @author felipedelclaux
 */
public class ViewAllPlatesSales extends javax.swing.JFrame {
objects.Item item; 
    /**
     * Creates new form ViewAllPlatesSales
     */
    public ViewAllPlatesSales() {
        initComponents();
        bundle();
        getContentPane().setBackground(Color.white); 
        
    }
    private void bundle(){ // Algorithm to bring all the items from the same batch together
	item = ViewInfoSales.item;
	ArrayList<Integer> unq = new ArrayList<>();
	DecimalFormat df = new DecimalFormat("##.00");
        SimpleDateFormat datef = new SimpleDateFormat("dd/MM/yyyy");
	unq.add(0);
	for(int a = 0; a<item.plates.size();a++){
            int countun = 0;
            for(int k = 0; k<unq.size();k++){
                if(!(item.plates.get(a).price == item.plates.get(unq.get(k)).price && item.plates.get(a).cost == item.plates.get(unq.get(k)).cost && item.plates.get(a).location.equals(item.plates.get(unq.get(k)).location) && datef.format(item.plates.get(a).dateSold).equals(datef.format(item.plates.get(unq.get(k)).dateSold)))){
                    countun++;
                }
            }
            if(countun == unq.size()){
                unq.add(a);
            }
	}
	for(int u = 0; u<unq.size();u++){//bundles up all the unique plates in item
            double price = item.plates.get(unq.get(u)).price;
            double cost = item.plates.get(unq.get(u)).cost;
            String location = item.plates.get(unq.get(u)).location;
            Date date = item.plates.get(unq.get(u)).dateSold;
            int count = 0; //instantiates count of plates plates with unique combo of price,cost,location, and date sold to zero
            double totalProfit = 0;
            for(int i = 0; i<item.plates.size();i++){//loops through all plates to find all plates with the same combo of price,cost,location,dateSold 
                if(price == item.plates.get(i).price && cost == item.plates.get(i).cost && location.equals(item.plates.get(i).location) && datef.format(date).equals(datef.format(item.plates.get(i).dateSold))){
                    count++; //increases count if plate with that combo is found
                    totalProfit += item.plates.get(i).price - item.plates.get(i).cost; //updates total profi
                }
            }
            DefaultTableModel model = (DefaultTableModel) DisplayTable.getModel(); 
            Object rowData[] = new Object[6];
            rowData[0] = count;
            rowData[1] = Double.parseDouble(df.format(price));
            rowData[2] = Double.parseDouble(df.format(cost));
            rowData[3] = Double.parseDouble(df.format(totalProfit));
            rowData[4] = location;
            rowData[5] = datef.format(date);
            model.addRow(rowData); //displays this item on the table
	}
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Amount Sold", "Price Sold", "Cost", "Total Profit", "Customer", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DisplayTable);

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllPlatesSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllPlatesSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllPlatesSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllPlatesSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllPlatesSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DisplayTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
