package GUI;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author felipedelclaux
 */
public class ViewAllPlatesInventory extends javax.swing.JFrame {
    objects.Item item;
    /**
     * Creates new form ViewAllPlatesInventory
     */
    public ViewAllPlatesInventory() {
        initComponents();
        getContentPane().setBackground(Color.white); 
        bundle();
    }
    
    private void bundle(){
	item = ViewInfoInventory.item;
	ArrayList<Integer> unq = new ArrayList<>();
	DecimalFormat df = new DecimalFormat("##.00");
	unq.add(0);
	for(int a = 0; a<item.plates.size();a++){
            int countun = 0;
            for(int k = 0; k<unq.size();k++){
                if(!(item.plates.get(a).cost == item.plates.get(unq.get(k)).cost && item.plates.get(a).location.equals(item.plates.get(unq.get(k)).location))){
                    countun++;
                }
            }
            if(countun == unq.size()){
                unq.add(a);
            }
	}
	for(int u = 0; u<unq.size();u++){
            double cost = item.plates.get(unq.get(u)).cost;
            String location = item.plates.get(unq.get(u)).location;
            int count = 0;
            for(int i = 0;i<item.plates.size();i++){
                if(location.equals(item.plates.get(i).location) && cost == item.plates.get(i).cost){
                    count++;
                }
            }
            DefaultTableModel model = (DefaultTableModel) DisplayTable.getModel();
            Object rowData[] = new Object[3];
            rowData[0] = count;
            rowData[1] = cost;
            rowData[2] = location;
            model.addRow(rowData); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayTable = new javax.swing.JTable();
        Done = new javax.swing.JButton();
        ChangeLocation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Amount", "Cost", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DisplayTable);

        Done.setText("Done");
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });

        ChangeLocation.setText("Change Location");
        ChangeLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ChangeLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Done)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChangeLocation)
                    .addComponent(Done, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ChangeLocation, Done});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_DoneActionPerformed

    private void ChangeLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeLocationActionPerformed
        if(DisplayTable.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this,
            "Please select a row before clicking this button",
            "Error",
            JOptionPane.ERROR_MESSAGE);
	}
	else{
            int r = DisplayTable.getSelectedRow();
            double c = Double.parseDouble( DisplayTable.getValueAt(r,1).toString());
            String l = (String) DisplayTable.getValueAt(r,2);
            new ChangeLocation(item, c, l).setVisible(true);
            this.dispose();
}        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeLocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllPlatesInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllPlatesInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllPlatesInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllPlatesInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllPlatesInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeLocation;
    private javax.swing.JTable DisplayTable;
    private javax.swing.JButton Done;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
